include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
    - "**.g.dart"
    - "**.gen.dart"
  errors:
    always_declare_return_types: error
    camel_case_types: error
    dead_code: error
    empty_statements: error
    file_names: error
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    missing_required_param: error
    missing_return: error
    no_duplicate_case_values: error
    prefer_single_quotes: error
    unrelated_type_equality_checks: error

linter:
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_empty_else
    - avoid_print
    - avoid_unnecessary_containers
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - empty_statements
    - file_names
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - member-ordering:
        alphabetize: true
        order:
          - public-fields
          - private-fields
          - constructors
    - no_duplicate_case_values
    - no_logic_in_create_state
    - omit_local_variable_types
    - only_throw_errors
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_void_to_null
    - prefer-trailing-comma:
        break-on: 2
    - sized_box_for_whitespace
    - sort_pub_dependencies
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_new
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_key_in_widget_constructors
    - use_string_buffers
