name: binance_api
description: A Dart package that providing access to the Binance exchange APIs.
version: 0.0.1-dev.2
repository: https://github.com/VadimMalykhin/binance-api.dart
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.2
  dio: ^5.1.1
  equatable: ^2.0.5
  web_socket_channel: ^2.3.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
