name: binance_api
description: A Dart package that providing access to the Binance exchange APIs.
version: 0.0.1-dev.0
repository: https://github.com/VadimMalykhin/binance-api.dart
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  convert: ^3.0.1
  crypto: ^3.0.2
  dio: ^4.0.6
  equatable: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.20.1
