name: CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        sdk: [stable, beta]
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart run test
